config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index", to: "home#index"
  get "/home", to: "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

require "net/https"
require "json"

class HomeController < ApplicationController
  include HomeHelper

  def index
    @page = page_state
    @search_query = params[:query].present? ? params[:query].tr(" ", "_") : nil

    page_response = Rails.cache.fetch("retrieve_beers_page_#{@page}_search_#{@search_query}", expires_in: 12.hours) { retrieve_beers(@page, @search_query) }
    @response_body = JSON.parse(page_response)

    next_page = Rails.cache.fetch("retrieve_beers_page_#{@page + 1}_search_#{@search_query}", expires_in: 12.hours) { retrieve_beers(@page + 1, @search_query) }
    @next_page = JSON.parse(next_page)
  end

  private
    def retrieve_beers(page, search_query)
      # PunkApi cannot handle empty parameters
      # so we fully exclude it in the url if
      # no value is provided
      if not search_query.nil?
        filter_by_query = "&beer_name=#{search_query}"
      end

      assembled_url = "#{BEER_ENDPOINT}/?per_page=10&page=#{page}#{filter_by_query}"

      # Used for debugging only
      # puts "Sent request to: #{assembled_url}"

      uri = URI(assembled_url)
      Net::HTTP.get(uri)
    end

    def page_state
      params[:page].nil? ? 1 : params[:page].to_i
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  BEER_ENDPOINT = "https://api.punkapi.com/v2/beers"
end

app/views/home/_modal.html.erb
<div class="modal fade" id="modal-id-<%= row["id"] %>" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= row["name"] %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
          <strong>Description:</strong> <%= row["description"] %>
        </p>
        <p>
          <strong>Food pairing:</strong> <%= row["food_pairing"].join(', ') %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Sounds good!</button>
      </div>
    </div>
  </div>
</div>

app/views/home/_pagination.html.erb
<% if @page != 1 %>
  <% if @next_page.empty? %>
    <% (@page - 2).upto(@page) do |i| %>
      <% next if i == 0 %>

      <li class="page-item <%= @page === i ? 'active' : nil %>">
        <%= link_to i, home_path(page: i, query: @search_query), class: 'page-link' %>
      </li>
    <% end %>
  <% else %>
    <% (@page - 1).upto(@page + 1) do |i| %>
      <% next if i == 0 %>

      <li class="page-item <%= @page === i ? 'active' : nil %>">
      <%= link_to i, home_path(page: i, query: @search_query), class: 'page-link' %>
    </li>
    <% end %>
  <% end %>
<% else %>
  <!-- For Page 1 only -->
  <% if @next_page.empty? %>
    <li class="page-item active">
      <%= link_to @page, home_path(page: @page, query: @search_query), class: 'page-link' %>
    </li>
  <% else %>
    <% @page.upto(@page + 2) do |i| %>
      <li class="page-item <%= @page === i ? 'active' : nil %>">
        <%= link_to i, home_path(page: i, query: @search_query), class: 'page-link' %>
      </li>
    <% end %>
  <% end %>
<% end %>

app/views/home/_row.html.erb
<% table.each do |row| %>
  <tr>
    <td>
      <%= row["name"] %>
    </td>
    <td>
      <%= row["abv"] %>
    </td>
    <td>
      <%= link_to 'Read more', nil, type: 'button', class: 'btn btn-primary', 'data-bs-toggle': 'modal', 'data-bs-target': "#modal-id-#{row["id"]}" %>
      <%= render partial: 'modal', locals: { row: row } %>
    </td>
  </tr>
<% end %>

app/views/home/index.html.erb
<div class="container px-5">

  <div class="pt-3 pb-3">
    <h1 class="display-6">Home#index</h1>
    <div>
      <p class="lead">Page <%= @page %></p>
    </div>
  </div>

  <%= form_with url: home_path(page: @page, query: nil), method: :get, class: 'input-group pt-3 pb-3' do |f| %>
    <%= f.text_field :query, placeholder: 'Ale, Punk IPA...', type: 'text', class: 'form-control' %>
    <%= f.submit 'Search', class: 'btn btn-outline-secondary', type: 'button' %>
  <% end %>

  <% if not @search_query.nil? %>
    <p class="pt-3 pb-2 text-muted">You searched: <strong><%= params[:query] %></strong></p>
  <% end %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th class="col">Name</th>
        <th class="col">Alcohol by volume (%)</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'row', locals: { table: @response_body } %>
    </tbody>
  </table>

  <% if @response_body.empty? %>
    <p class="text-muted">Nothing found...</p>
  <% end %>

  <nav aria-label="Page navigation">
    <ul class="pagination">
      <li class="page-item">
        <%= link_to 'Home', home_path, class: 'page-link' %>
      </li>

      <li class="page-item <%= @page === 1 ? 'disabled' : nil %>">
        <%= link_to 'Previous', home_path(page: @page - 1, query: @search_query), class: 'page-link' %>
      </li>

      <%= render partial: 'pagination', locals: { body: @response_body } %>

      <li class="page-item <%= @response_body.empty? || @next_page.empty? ? 'disabled' : nil %>">
        <%= link_to 'Next', home_path(page: @page + 1, query: @search_query), class: 'page-link' %>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodWithBeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>